remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Aditya Pratap Singh
description: Freelance bot developer skilled in JavaScript, Node.js, and Python — creator of SnowBot, FAB, TipBot, FUB, and more.
